import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import "./custom.css";
import { getStore, isLinkpeConfigured } from "@/lib/linkpe";

// Map the store's theme colors onto the CSS variables the UI reads. Only set the
// ones present so globals.css defaults fill any gaps.
function themeVars(theme?: { primary_color: string | null; secondary_color: string | null; accent_color: string | null }) {
  const vars: Record<string, string> = {};
  if (theme?.primary_color) vars["--store-primary"] = theme.primary_color;
  if (theme?.secondary_color) vars["--store-secondary"] = theme.secondary_color;
  if (theme?.accent_color) vars["--store-accent"] = theme.accent_color;
  return vars as React.CSSProperties;
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const store = isLinkpeConfigured() ? await getStore().catch(() => null) : null;

  return (
    <html
      lang="en"
      className={`${interSans.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" style={themeVars(store?.theme)}>
        {children}
        {modal}
      </body>
    </html>
  );
}
